# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Leland Speech and Debate App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Leland Speech and Debate App
# add the Firebase pod for Google Analytics
pod 'Firebase'
pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'
pod 'DropDown'
pod 'Google-Mobile-Ads-SDK'
pod 'VegaScrollFlowLayout'
pod 'RAMReel'
pod 'GravitySliderFlowLayout'
pod "BouncyLayout"
pod 'CardsLayout'
pod 'CarLensCollectionViewLayout', '~> 1.2.0'
pod 'VerticalCardSwiper'
pod 'AnimatedCollectionViewLayout'
pod 'FoldingCell'



# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
  target 'Leland Speech and Debate AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Leland Speech and Debate AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
